title: John Doe's
author: John Doe
description: John Doe's notes

# nav menu for your site
menu:
  Home: /
  About: https://github.com/haishanh/notedown

source_dir: demo_notes
output_dir: output
theme_dir: themes/default

# site
#
# if you are using a sub domain for example, http://example.com/notes
# then root should be set to '/notes/' instead of '/'
root: /
per_page: 5
